version: '3.2'
services:
  go:
    # image: lundgren2/tdde06-go
    build: go
    container_name: go-app
    restart: always
    env_file: .env.docker
    ports:
      - "8080:8080"
    volumes:
      - ./go:/go/src/app
      - logvolume01:/var/log
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    container_name: postgres-server
    restart: always
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./postgres/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env.docker

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    restart: always
    volumes:
      - ./nginx/config/nginx.conf:/nginx.conf
    command: /bin/sh -c "nginx -c /nginx.conf -g 'daemon off;'"
    ports:
      - "8000:80"
    links:
      - go
volumes:
  logvolume01: {}
