version: '3.2'
services:
  go-project:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - nginx
    - postgres
  postgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false

      - DB_USER=
      - DB_PASS=
      - DB_NAME=
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
  volumes:
- /srv/docker/postgresql:/var/lib/postgresql
  nginx:
    image: nginx
volumes:
  logvolume01: {}
